name: Dump Database

on:
  push:
    paths:
      - "db/**"
  workflow_dispatch:

jobs:
  dump-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SQLite environment
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Dump tables to SQL
        run: |
          sqlite3 db/torikizoku.db ".output ./db/dump.sql" ".dump"

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

          git add db/dump.sql
          if git diff --cached --quiet; then
            echo "No changes detected in dump directory. Skipping commit and push."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git fetch
          git pull
          git commit -m "chore: Update dump file"
          git push origin main
