name: Update

on:
  push:
    paths:
      - "db/**"
      - "tools/converter/**"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.3"
          check-latest: true
          cache-dependency-path: |
            tools/converter/go.sum

      - name: Update files
        run: cd tools/converter && go run cmd/main.go --csv --json --md

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

          git add dist
          if git diff --cached --quiet; then
            echo "No changes detected in dump directory. Skipping commit and push."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git fetch
          git pull
          git commit -m "chore: Update files"
          git push origin main
